In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])  # Create a rank 1 array
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # Change an element of the array
print(a)     

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [3]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


In [5]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)

[[0. 0.]
 [0. 0.]]


In [6]:
b = np.ones((1,2))   # Create an array of all ones
print(b)

[[1. 1.]]


In [27]:
c = np.full((2,2), 7) # Create a constant array
print(c)

[[7 7]
 [7 7]]


In [10]:
d = np.eye(2)        # Create a 2x2 identity matrix
print(d)

[[1. 0.]
 [0. 1.]]


In [13]:
e = np.random.random((2,2)) # Create an array filled with random values
print(e)

[[0.10213364 0.61991632]
 [0.71546385 0.86424032]]


#Practice Arrays

In [25]:
test = np.r_[1:16].reshape([3,5])
print(test)

TypeError: 'tuple' object is not callable